deploy_dbt:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('DEPLOY_DBT_SNOWFLAKE_ACCOUNT_ID') }}"

      # User/password auth
      user: "{{ env_var('DEPLOY_DBT_SNOWFLAKE_USERNAME') }}"
      password: "{{ env_var('DEPLOY_DBT_SNOWFLAKE_PASSWORD') }}"

      role: dbt_dev_role
      database: dbt_dev_db
      warehouse: dbt_dev_wh
      # in the future you should switch this schema to use a new environment variable
      # definitely switch this to your schema though
      schema: DBT_RSOANKAMBLE
      threads: 4
      client_session_keep_alive: False
    prod:
      type: snowflake
      account: "{{ env_var('DEPLOY_DBT_PROD_SNOWFLAKE_ACCOUNT_ID') }}"

      # User/password auth
      user: "{{ env_var('DEPLOY_DBT_PROD_SNOWFLAKE_USERNAME') }}"
      password: "{{ env_var('DEPLOY_DBT_PROD_SNOWFLAKE_PASSWORD') }}"

      role: DBT_PROD_ROLE
      database: dbt_prod_db
      warehouse: dbt_prod_wh
      schema: dbt_prod_schema
      threads: 4
      client_session_keep_alive: False
